config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get '/about',to: 'pages#about'

  resources :contacts, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email,  :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "Contact Form",
      :to => "gw.website10@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      redirect_to root_path
      flash[:notice] = "Thanks for your message, we will get back you soon"
    else
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <div class="form-container">
    <p><%= link_to 'GV-WEB', root_path  %> > contact form</p>
    <h2>Contact Form</h2>
    <%= simple_form_for @contact do |f| %>
    <h3>Name<strong style="color:red; font-size: 16px;">*</strong></h3>
    <div class="form-group">
      <%= f.input :name, input_html: { class: "form-control form-control-lg"}, label: false%>
    </div>
    <h3>Email address<strong style="color:red; font-size: 16px;">*</strong></h3>
    <div class="form-group">
      <%= f.input :email, input_html: { class: "form-control form-control-lg"}, label: false, placeholder: "name@example.com" %>
    </div>
    <h3>Message<strong style="color:red; font-size: 16px;">*</strong></h3>
    <div class="form-group">
     <%= f.input :message, :as => :text, input_html: { class: "form-control", id:"exampleFormControlTextarea1", rows:"5" }, label: false %>
    </div>
    <h4>Please enter the details of your request. A member of our support staff will respond as soon as possible.</h4>
    <div class="hidden">
      <%= f.input :nickname %>
      <p>hola</p>
    </div>
    <div class="guillo w-100">
      <%= f.button :submit, class: "btn btn-primary btn-lg btn-block" %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>GW web</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-wrapper">
  <h2>ABOUT ME</h2>
  <div class="about-container">
    <div class="image-about">
      <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1584295662/Captura_de_Pantalla_2019-10-07_a_la_s_18.25.38.png" alt="">
    </div>
    <div class="about-description">
      <p>I've completed Le Wagon coding bootcamp (Buenos Aires, Batch #198 - october 2018) to add technical skills to my creative profile (HTML, CSS, Bootstrap, Javascript, RubyOnRails)🚀<br>
      Passionate about the tech/startup environment, I have always been interested in creating and managing my own projects.<br>
      Indeed, I created and developed Miranda App, a language learning plattaform (2018/2019).<br>
      After this amazing entrepreneurial experience, I keep working as a freelance creating several projects. At the same time working as TA in Lewagon Buenos Aires helping new tech students during the bootcamp.<br>
      Currently working as developer in GV-WEB </p>
      <div class="description-footer">
        <a href="https://www.linkedin.com/in/guillermovareladagnillo/" class="btn btn-primary" target="blank"><i class="fab fa-linkedin"></i> Linkedin</a>
        <a href="https://github.com/guillo16" class="btn btn-dark" target="blank"><i class="fab fa-github"></i> Github</a>
      </div>
    </div>
  </div>
  <!-- skills part of the page -->
  <div class="skills">
      <h2 class="mt-3">SKILLS</h2>
      <div class="skills-wrapper">
        <div class="skills-container1">
          <div class="skills-content">
           <p><img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1584376879/iconfinder_Ruby_on_Rails_2_282804_1.png" style="width: 20px; border: 1px solid black;"alt=""> RUBY ON RAILS</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar bg-success" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 100%">100%</div>
            </div>
          </div>
          <div class="skills-content">
            <p><i class="far fa-gem"> </i> RUBY</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar bg-success" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 100%">100%</div>
            </div>
          </div>
          <div class="skills-content">
            <p><i class="fab fa-html5"></i> HTML5</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar bg-success" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 100%">100%</div>
            </div>
          </div>
          <div class="skills-content">
            <p><i class="fab fa-css3"></i> SCSS</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar bg-success" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 100%">100%</div>
            </div>
          </div>
          <div class="skills-content">
            <p><i class="fab fa-js"></i> JAVSCRIPT</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 60%;" >60%</div>
            </div>
          </div>
          <div class="skills-content">
            <p><i class="fab fa-react"></i> REACT</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 45%"> 45%</div>
            </div>
          </div>
        </div>
        <div class="skills-container1">

          <div class="skills-content">
            <p><i class="fab fa-github-square"></i> GITHUB</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar bg-success" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 100%">100%</div>
            </div>
          </div>
          <div class="skills-content">
            <p><i class="fas fa-bold"></i> BOOTSTRAP</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar bg-success" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 100%">100%</div>
            </div>
          </div>
          <div class="skills-content">
            <p><i class="fab fa-cc-stripe"></i> STRIPE</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 80%">80%</div>
            </div>
          </div>
          <div class="skills-content">
            <p><i class="fas fa-database"></i> SQL</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%">75%</div>
            </div>
          </div>
          <div class="skills-content">
            <p><i class="fab fa-git-square"></i> GIT</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%">75%</div>
            </div>
          </div>
          <div class="skills-content">
            <p><img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1584371101/iconfinder_jquery_282807.png" style="width: 20px;" alt=""> JQUERY</p>
            <div class="progress" style="height: 20px;">
              <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 60%">60%</div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
<div class="skills-footer">
  <%= link_to  new_contact_path, class: "contact-button" do %>
    Get In Touch
  <% end %>
</div>

app/views/pages/home.html.erb
<section id="banner">
  <%= render 'shared/banner' %>
</section>
<section id="portfolio">
  <%= render 'shared/portfolio' %>
</section>
<section id="team">
 <%= render 'shared/team' %>
</section>
<section id="icons">
  <%= render 'shared/icons' %>
</section>
<section id="carousel">
  <%= render 'shared/carousel' %>
</section>

<section id="social">
  <%= render 'shared/social'%>
</section>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://res.cloudinary.com/dw7ox75dg/image/upload/v1559064653/photo-1534972195531-d756b9bfa9f2.jpg);">
  <div class="container">
    <h1>Build the website of your dreams </h1>
    <p>
      <span id="banner-typed-text"></span>
    </p>
    <%= link_to 'Contact us', new_contact_path, class: 'button-1' %>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1584300922/photo-1451187580459-43490279c0fa.jpg" class="d-block w-100" class="d-block w-100" alt="...">
      <div class="carousel-caption">
        <h5>"Your time is limited, so don't waste it living someone else's life. Don't let the noise of others' opinions drown out your own inner voice."</h5>
        <p>Steve Jobs - Apple founder</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1584300922/photo-1451187580459-43490279c0fa.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption">
        <h5>"If you only do things where you know the answer in advance, your company goes away. You don't choose your passions. Your passions choose you."</h5>
        <p>Jeff Bezos - Amazon CEO</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1584300922/photo-1451187580459-43490279c0fa.jpg" class="d-block w-100" class="d-block w-100" alt="...">
      <div class="carousel-caption">
        <h5>"Don’t compare yourself with anyone in this world… if you do so, you are insulting yourself."</h5>
        <p>Bill Gates - Microsoft owner</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="alert alert-primary" role="alert">
  <%= notice %> <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>
<% if alert %>
<div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
  <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    <p> Creation + Pasion + Technology</p>
    <%= link_to 'GV-WEB', root_path %>
  </div>
</div>

app/views/shared/_icons.html.erb
<div class="cards">
  <div class="card-1">
    <div class= "card-1-container">
      <i class="fas fa-shopping-cart"></i>
      <h2>Open your online shop. Sell everything you want with the best warranty</h2>
      <%= link_to contacts_path do %>
      Learn more <i class="fas fa-greater-than"></i>
      <% end %>
    </div>
  </div>
  <div class="card-2">
    <div class= "card-2-container">
      <h2>For your Company or personal business</h2>
      <h3>We can also build your blog or portfolio</h3>
      <%= link_to contacts_path do %>
      <p>Learn more <i class="fas fa-greater-than"></i></p>
      <% end %>
      <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/c_scale,w_825/v1585838317/Captura-de-pantalla-2019-11-13-a-las-14.45.05.png" alt="">
    </div>
  </div>

  <div class="card-3">
    <div class= "card-3-container">
        <i class="fas fa-mobile-alt"></i>
        <h2>Ready for Phones</h2>
      <h3>Your web will look cool in tablets and smartphones</h3>

      <%= link_to contacts_path do %>
      <p>Learn more <i class="fas fa-greater-than"></i></p>
      <% end %>
      <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/c_scale,w_802/v1585840344/1568121499_490816_1568143364_sumario_normal_recorte1.jpg" alt="">
    </div>
  </div>

  <div class="card-4" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dw7ox75dg/image/upload/c_scale,w_830/v1585841027/photo-1504639725590-34d0984388bd.jpg);">
    <div class= "card-4-container">
      <h2>In only weeks your can have your dream website</h1>
        <%= link_to contacts_path do %>
        Learn more <i class="fas fa-greater-than"></i>
        <% end %>
      </div>

    </div>

  </div>

app/views/shared/_navbar.html.erb
<div class="navbar-wrapper fixed-top">
  <div class="nabvar-logo">
    <%= link_to 'GV-WEB', root_path  %>
  </div>
  <div class="nabvar-content">
   <%= link_to "CONTACT", new_contact_path %>
   <%= link_to "SOCIAL", "#{root_path}#social" %>
 </div>
</div>

app/views/shared/_portfolio.html.erb
<div class="img-container">
  <div class="img-description">
    <br><br>
    <h1>The best designs</h1>
    <h3>We will help you choose the best web desings available for you.</h3>
  </div>
  <div class="images">
    <div class="images-1">
      <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1559070031/Captura_de_Pantalla_2019-05-28_a_la_s_15.51.48.png" alt="">
    </div>
    <div class="images-1">
     <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1559070062/Captura_de_Pantalla_2019-05-28_a_la_s_15.55.44.png" alt="">
   </div>
   <div class="images-1">
    <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1559070065/Captura_de_Pantalla_2019-05-28_a_la_s_15.56.24.png" alt="">
  </div>
  <div class="images-1">
    <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1559070083/Captura_de_Pantalla_2019-05-28_a_la_s_15.56.57.png" alt="">
  </div>
  <div class="images-1">
    <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1559070097/Captura_de_Pantalla_2019-05-28_a_la_s_15.59.09.png" alt="">
  </div>
  <div class="images-1">
    <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1559071454/Captura_de_Pantalla_2019-05-28_a_la_s_16.23.12.png" alt="">
  </div>
</div>
<br>

app/views/shared/_social.html.erb
 <div class="img-hover">
  <div class="hovereffect">
    <img class="img-responsive" src="https://images.unsplash.com/photo-1483389127117-b6a2102724ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1567&q=80" alt="">
    <div class="overlay">
      <h2></h2>
      <p class="set1">
        <a href="https://www.instagram.com/" target="blank">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="https://www.facebook.com/" target="blank">
          <i class="fab fa-facebook"></i>
        </a>
      </p>
      <hr>
      <hr>
      <p class="set2">
        <a href="https://twitter.com" target="blank">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="#">
          <i class="fab fa-dribbble"></i>
        </a>
      </p>
    </div>
  </div>
</div>

app/views/shared/_team.html.erb
<div class="content-container">
  <div class="content">
    <h1>We have the best professionals </h1>
    <p>The best professionals will help you to find the best design to achieve your dream website.</p>
    <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1559064764/photo-1517607537732-619ace47ec9e.jpg" alt="">
  </div>
  <div class="content-img">
    <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1559136299/photo-1522071820081-009f0129c71c.jpg" alt="">
  </div>
</div>
<div class="wrapper">
  <div class="img-1">
    <div class="hovereffect-1">
      <img class="img-responsive" src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1584295662/Captura_de_Pantalla_2019-10-07_a_la_s_18.25.38.png" alt="">
      <div class="overlay">
        <h2>Guillermo Varela</h2>
        <%= link_to 'ABOUT HIM' , about_path , class: 'info'%>
      </div>
    </div>
  </div>
  <div class="img-1">
    <div class="hovereffect-1">
      <img class="img-responsive" src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" alt="">
      <div class="overlay">
        <h2>Agustina Campos</h2>
        <%= link_to 'CONTACT HER' , new_contact_path , class: 'info'%>
      </div>
    </div>
  </div>
  <div class="img-1">
    <div class="hovereffect-1">
      <img class="img-responsive" src="https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80" alt="">
      <div class="overlay">
        <h2>Martin Hernandez</h2>
        <%= link_to 'CONTACT HIM' , new_contact_path , class: 'info'%>
      </div>
    </div>
  </div>
</div>